(define (problem cCrewPlanning_2crew_1day_40utilization)
	(:domain cCrewPlanning)
	(:objects )
	(:init 
		(act )
		(isnt-fin c1)
		(isnt-fin c2)
		(currentday-l c1 c1 d0)
		(currentday-l c2 c1 d0)
		(done_sleep-l c1 c1 d0)
		(done_sleep-l c2 c1 d0)
		(available-l c1 c1)
		(available-l c2 c1)
		(currentday-l c1 c2 d0)
		(currentday-l c2 c2 d0)
		(done_sleep-l c1 c2 d0)
		(done_sleep-l c2 c2 d0)
		(available-l c1 c2)
		(available-l c2 c2)
		(initiated-l c1 d1)
		(initiated-l c2 d1)
		(next-l c1 d0 d1)
		(next-l c2 d0 d1)
		(next-l c1 d1 d2)
		(next-l c2 d1 d2)
		(unused-l c1 e1)
		(unused-l c2 e1)
		(currentday-g c1 d0)
		(done_sleep-g c1 d0)
		(available-g c1)
		(currentday-g c2 d0)
		(done_sleep-g c2 d0)
		(available-g c2)
		(initiated-g d1)
		(next-g d0 d1)
		(next-g d1 d2)
		(unused-g e1)
		(= (mcs_finished-inv mcs1 d0) 0 )
		(= (mcs_finished-inv mcs1 d1) 0 )
		(= (mcs_finished-inv mcs1 d2) 0 )
		(= (mcs_finished-inv mcs2 d0) 0 )
		(= (mcs_finished-inv mcs2 d1) 0 )
		(= (mcs_finished-inv mcs2 d2) 0 )
		(= (changed-inv spaceshipFilter d0) 0 )
		(= (changed-inv spaceshipFilter d1) 0 )
		(= (changed-inv spaceshipFilter d2) 0 )
		(= (available-inv c1) 0 )
		(= (available-inv c2) 0 )
		(= (done_sleep-inv c1 d0) 0 )
		(= (done_sleep-inv c1 d1) 0 )
		(= (done_sleep-inv c1 d2) 0 )
		(= (done_sleep-inv c2 d0) 0 )
		(= (done_sleep-inv c2 d1) 0 )
		(= (done_sleep-inv c2 d2) 0 )
		(= (done_pre_sleep-inv c1 d0) 0 )
		(= (done_pre_sleep-inv c1 d1) 0 )
		(= (done_pre_sleep-inv c1 d2) 0 )
		(= (done_pre_sleep-inv c2 d0) 0 )
		(= (done_pre_sleep-inv c2 d1) 0 )
		(= (done_pre_sleep-inv c2 d2) 0 )
		(= (done_post_sleep-inv c1 d0) 0 )
		(= (done_post_sleep-inv c1 d1) 0 )
		(= (done_post_sleep-inv c1 d2) 0 )
		(= (done_post_sleep-inv c2 d0) 0 )
		(= (done_post_sleep-inv c2 d1) 0 )
		(= (done_post_sleep-inv c2 d2) 0 )
		(= (done_dpc-inv c1 d0) 0 )
		(= (done_dpc-inv c1 d1) 0 )
		(= (done_dpc-inv c1 d2) 0 )
		(= (done_dpc-inv c2 d0) 0 )
		(= (done_dpc-inv c2 d1) 0 )
		(= (done_dpc-inv c2 d2) 0 )
		(= (done_meal-inv c1 d0) 0 )
		(= (done_meal-inv c1 d1) 0 )
		(= (done_meal-inv c1 d2) 0 )
		(= (done_meal-inv c2 d0) 0 )
		(= (done_meal-inv c2 d1) 0 )
		(= (done_meal-inv c2 d2) 0 )
		(= (done_exercise-inv c1 d0) 0 )
		(= (done_exercise-inv c1 d1) 0 )
		(= (done_exercise-inv c1 d2) 0 )
		(= (done_exercise-inv c2 d0) 0 )
		(= (done_exercise-inv c2 d1) 0 )
		(= (done_exercise-inv c2 d2) 0 )
		(= (payload_act_done-inv pa1_1) 0 )
		(= (payload_act_done-inv pa1_2) 0 )
		(= (payload_act_done-inv pa1_3) 0 )
		(= (payload_act_done-inv pa1_4) 0 )
		(= (payload_act_done-inv pa1_5) 0 )
		(= (payload_act_done-inv pa1_6) 0 )
		(= (payload_act_completed-inv pa1_1 d0) 0 )
		(= (payload_act_completed-inv pa1_1 d1) 0 )
		(= (payload_act_completed-inv pa1_1 d2) 0 )
		(= (payload_act_completed-inv pa1_2 d0) 0 )
		(= (payload_act_completed-inv pa1_2 d1) 0 )
		(= (payload_act_completed-inv pa1_2 d2) 0 )
		(= (payload_act_completed-inv pa1_3 d0) 0 )
		(= (payload_act_completed-inv pa1_3 d1) 0 )
		(= (payload_act_completed-inv pa1_3 d2) 0 )
		(= (payload_act_completed-inv pa1_4 d0) 0 )
		(= (payload_act_completed-inv pa1_4 d1) 0 )
		(= (payload_act_completed-inv pa1_4 d2) 0 )
		(= (payload_act_completed-inv pa1_5 d0) 0 )
		(= (payload_act_completed-inv pa1_5 d1) 0 )
		(= (payload_act_completed-inv pa1_5 d2) 0 )
		(= (payload_act_completed-inv pa1_6 d0) 0 )
		(= (payload_act_completed-inv pa1_6 d1) 0 )
		(= (payload_act_completed-inv pa1_6 d2) 0 )
		(= (next-inv d0 d0) 0 )
		(= (next-inv d0 d1) 0 )
		(= (next-inv d0 d2) 0 )
		(= (next-inv d1 d0) 0 )
		(= (next-inv d1 d1) 0 )
		(= (next-inv d1 d2) 0 )
		(= (next-inv d2 d0) 0 )
		(= (next-inv d2 d1) 0 )
		(= (next-inv d2 d2) 0 )
		(= (currentday-inv c1 d0) 0 )
		(= (currentday-inv c1 d1) 0 )
		(= (currentday-inv c1 d2) 0 )
		(= (currentday-inv c2 d0) 0 )
		(= (currentday-inv c2 d1) 0 )
		(= (currentday-inv c2 d2) 0 )
		(= (initiated-inv d0) 0 )
		(= (initiated-inv d1) 0 )
		(= (initiated-inv d2) 0 )
		(= (unused-inv e1) 0 )
	)
	(:goal (and (failure ) (fin c1) (fin c2)))
)