(define (problem cdrink-prob1)
	(:domain cdrink-world)
	(:objects )
	(:init 
		(act )
		(on-table-l person1 cup1)
		(on-table-l person2 cup1)
		(isnt-full-l person1 cup1)
		(isnt-full-l person2 cup1)
		(thirsty-l person1 person1)
		(thirsty-l person2 person1)
		(thirsty-l person1 person2)
		(thirsty-l person2 person2)
		(clear-l person1 person1)
		(clear-l person2 person1)
		(clear-l person1 person2)
		(clear-l person2 person2)
		(on-table-g cup1)
		(isnt-full-g cup1)
		(thirsty-g person1)
		(thirsty-g person2)
		(clear-g person1)
		(clear-g person2)
		(= (thirsty-inv person1) 0 )
		(= (thirsty-inv person2) 0 )
		(= (isnt-thirsty-inv person1) 0 )
		(= (isnt-thirsty-inv person2) 0 )
		(= (hold-cup-inv person1 cup1) 0 )
		(= (hold-cup-inv person2 cup1) 0 )
		(= (isnt-hold-cup-inv person1 cup1) 0 )
		(= (isnt-hold-cup-inv person2 cup1) 0 )
		(= (clear-inv person1) 0 )
		(= (clear-inv person2) 0 )
		(= (isnt-clear-inv person1) 0 )
		(= (isnt-clear-inv person2) 0 )
		(= (on-table-inv cup1) 0 )
		(= (isnt-on-table-inv cup1) 0 )
		(= (full-inv cup1) 0 )
		(= (isnt-full-inv cup1) 0 )
		(on-table-not-wt person1 cup1)
		(on-table-not-wt person2 cup1)
	)
	(:goal (and (failure ) (fin person1) (fin person2)))
)